//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 31.10.2016 13:36:53
namespace MediApp.DbServices
{
    
    /// <summary>
    /// There are no comments for PatientsContext in the schema.
    /// </summary>
    public partial class PatientsContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PatientsContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PatientsContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WcfService.Entities", "MediApp.DbServices");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MediApp.DbServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WcfService.Entities.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Illness> TableIllness
        {
            get
            {
                if ((this._TableIllness == null))
                {
                    this._TableIllness = base.CreateQuery<Illness>("TableIllness");
                }
                return this._TableIllness;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Illness> _TableIllness;
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> TableIllnessHasSymptom
        {
            get
            {
                if ((this._TableIllnessHasSymptom == null))
                {
                    this._TableIllnessHasSymptom = base.CreateQuery<IllnessHasSymptom>("TableIllnessHasSymptom");
                }
                return this._TableIllnessHasSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> _TableIllnessHasSymptom;
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Symptom> TableSymptom
        {
            get
            {
                if ((this._TableSymptom == null))
                {
                    this._TableSymptom = base.CreateQuery<Symptom>("TableSymptom");
                }
                return this._TableSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Symptom> _TableSymptom;
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> TableLifeFuncMeasure
        {
            get
            {
                if ((this._TableLifeFuncMeasure == null))
                {
                    this._TableLifeFuncMeasure = base.CreateQuery<LifeFuncMeasure>("TableLifeFuncMeasure");
                }
                return this._TableLifeFuncMeasure;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> _TableLifeFuncMeasure;
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Patient> TablePatient
        {
            get
            {
                if ((this._TablePatient == null))
                {
                    this._TablePatient = base.CreateQuery<Patient>("TablePatient");
                }
                return this._TablePatient;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Patient> _TablePatient;
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> TablePatientWasSick
        {
            get
            {
                if ((this._TablePatientWasSick == null))
                {
                    this._TablePatientWasSick = base.CreateQuery<PatientWasSick>("TablePatientWasSick");
                }
                return this._TablePatientWasSick;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> _TablePatientWasSick;
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllness(Illness illness)
        {
            base.AddObject("TableIllness", illness);
        }
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllnessHasSymptom(IllnessHasSymptom illnessHasSymptom)
        {
            base.AddObject("TableIllnessHasSymptom", illnessHasSymptom);
        }
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableSymptom(Symptom symptom)
        {
            base.AddObject("TableSymptom", symptom);
        }
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableLifeFuncMeasure(LifeFuncMeasure lifeFuncMeasure)
        {
            base.AddObject("TableLifeFuncMeasure", lifeFuncMeasure);
        }
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatient(Patient patient)
        {
            base.AddObject("TablePatient", patient);
        }
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatientWasSick(PatientWasSick patientWasSick)
        {
            base.AddObject("TablePatientWasSick", patientWasSick);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WcfService.Entities\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/" +
                "edm\"><EntityType Name=\"Illness\"><Key><PropertyRef Name=\"Id\" /></Key><Property Na" +
                "me=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xm" +
                "lns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Nam" +
                "e=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" />" +
                "</EntityType><EntityType Name=\"IllnessHasSymptom\"><Key><PropertyRef Name=\"Illnes" +
                "sHasSymptomId\" /></Key><Property Name=\"IllnessHasSymptomId\" Type=\"Edm.Int32\" Nul" +
                "lable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.micro" +
                "soft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Priority\" Type=\"Edm.Int32" +
                "\" Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int32\" Nullable=\"false" +
                "\" /><Property Name=\"SymptomId\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationPr" +
                "operty Name=\"Illness\" Relationship=\"WcfService.Entities.IllnessHasSymptom_Illnes" +
                "s\" ToRole=\"IllnessHasSymptom_Illness_Target\" FromRole=\"IllnessHasSymptom_Illness" +
                "_Source\" /><NavigationProperty Name=\"Symptom\" Relationship=\"WcfService.Entities." +
                "IllnessHasSymptom_Symptom\" ToRole=\"IllnessHasSymptom_Symptom_Target\" FromRole=\"I" +
                "llnessHasSymptom_Symptom_Source\" /></EntityType><EntityType Name=\"Symptom\"><Key>" +
                "<PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/" +
                "ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLength=" +
                "\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><EntityType Name=\"LifeFu" +
                "ncMeasure\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schema" +
                "s.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Temp\" Type=\"Edm.Do" +
                "uble\" Nullable=\"false\" /><Property Name=\"LowPressure\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><Property Name=\"HighPressure\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pro" +
                "perty Name=\"Pulse\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"PatientId" +
                "\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Patient\" Relatio" +
                "nship=\"WcfService.Entities.LifeFuncMeasure_Patient\" ToRole=\"LifeFuncMeasure_Pati" +
                "ent_Target\" FromRole=\"LifeFuncMeasure_Patient_Source\" /></EntityType><EntityType" +
                " Name=\"Patient\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://s" +
                "chemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"FstName\" Type" +
                "=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Nam" +
                "e=\"Surname\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\"" +
                " /><Property Name=\"Sex\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"He" +
                "ight\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Email\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Pass\" Ty" +
                "pe=\"Edm.Binary\" MaxLength=\"Max\" FixedLength=\"false\" /></EntityType><EntityType N" +
                "ame=\"PatientWasSick\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"htt" +
                "p://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Date\" Ty" +
                "pe=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"PatientId\" Type=\"Edm.Int32\"" +
                " Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int32\" Nullable=\"false\"" +
                " /><NavigationProperty Name=\"Illness\" Relationship=\"WcfService.Entities.PatientW" +
                "asSick_Illness\" ToRole=\"PatientWasSick_Illness_Target\" FromRole=\"PatientWasSick_" +
                "Illness_Source\" /><NavigationProperty Name=\"Patient\" Relationship=\"WcfService.En" +
                "tities.PatientWasSick_Patient\" ToRole=\"PatientWasSick_Patient_Target\" FromRole=\"" +
                "PatientWasSick_Patient_Source\" /></EntityType><Association Name=\"IllnessHasSympt" +
                "om_Illness\"><End Type=\"WcfService.Entities.Illness\" Role=\"IllnessHasSymptom_Illn" +
                "ess_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfSe" +
                "rvice.Entities.IllnessHasSymptom\" Role=\"IllnessHasSymptom_Illness_Source\" Multip" +
                "licity=\"*\" /><ReferentialConstraint><Principal Role=\"IllnessHasSymptom_Illness_T" +
                "arget\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"IllnessHasSymptom_I" +
                "llness_Source\"><PropertyRef Name=\"IllnessId\" /></Dependent></ReferentialConstrai" +
                "nt></Association><Association Name=\"IllnessHasSymptom_Symptom\"><End Type=\"WcfSer" +
                "vice.Entities.Symptom\" Role=\"IllnessHasSymptom_Symptom_Target\" Multiplicity=\"1\">" +
                "<OnDelete Action=\"Cascade\" /></End><End Type=\"WcfService.Entities.IllnessHasSymp" +
                "tom\" Role=\"IllnessHasSymptom_Symptom_Source\" Multiplicity=\"*\" /><ReferentialCons" +
                "traint><Principal Role=\"IllnessHasSymptom_Symptom_Target\"><PropertyRef Name=\"Id\"" +
                " /></Principal><Dependent Role=\"IllnessHasSymptom_Symptom_Source\"><PropertyRef N" +
                "ame=\"SymptomId\" /></Dependent></ReferentialConstraint></Association><Association" +
                " Name=\"LifeFuncMeasure_Patient\"><End Type=\"WcfService.Entities.Patient\" Role=\"Li" +
                "feFuncMeasure_Patient_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></En" +
                "d><End Type=\"WcfService.Entities.LifeFuncMeasure\" Role=\"LifeFuncMeasure_Patient_" +
                "Source\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"LifeFuncMeasu" +
                "re_Patient_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"LifeFun" +
                "cMeasure_Patient_Source\"><PropertyRef Name=\"PatientId\" /></Dependent></Referenti" +
                "alConstraint></Association><Association Name=\"PatientWasSick_Illness\"><End Type=" +
                "\"WcfService.Entities.Illness\" Role=\"PatientWasSick_Illness_Target\" Multiplicity=" +
                "\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfService.Entities.PatientWas" +
                "Sick\" Role=\"PatientWasSick_Illness_Source\" Multiplicity=\"*\" /><ReferentialConstr" +
                "aint><Principal Role=\"PatientWasSick_Illness_Target\"><PropertyRef Name=\"Id\" /></" +
                "Principal><Dependent Role=\"PatientWasSick_Illness_Source\"><PropertyRef Name=\"Ill" +
                "nessId\" /></Dependent></ReferentialConstraint></Association><Association Name=\"P" +
                "atientWasSick_Patient\"><End Type=\"WcfService.Entities.Patient\" Role=\"PatientWasS" +
                "ick_Patient_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Typ" +
                "e=\"WcfService.Entities.PatientWasSick\" Role=\"PatientWasSick_Patient_Source\" Mult" +
                "iplicity=\"*\" /><ReferentialConstraint><Principal Role=\"PatientWasSick_Patient_Ta" +
                "rget\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"PatientWasSick_Patie" +
                "nt_Source\"><PropertyRef Name=\"PatientId\" /></Dependent></ReferentialConstraint><" +
                "/Association><EntityContainer Name=\"PatientsContext\" m:IsDefaultEntityContainer=" +
                "\"true\"><EntitySet Name=\"TableIllness\" EntityType=\"WcfService.Entities.Illness\" /" +
                "><EntitySet Name=\"TableIllnessHasSymptom\" EntityType=\"WcfService.Entities.Illnes" +
                "sHasSymptom\" /><EntitySet Name=\"TableSymptom\" EntityType=\"WcfService.Entities.Sy" +
                "mptom\" /><EntitySet Name=\"TableLifeFuncMeasure\" EntityType=\"WcfService.Entities." +
                "LifeFuncMeasure\" /><EntitySet Name=\"TablePatient\" EntityType=\"WcfService.Entitie" +
                "s.Patient\" /><EntitySet Name=\"TablePatientWasSick\" EntityType=\"WcfService.Entiti" +
                "es.PatientWasSick\" /><AssociationSet Name=\"IllnessHasSymptom_Illness\" Associatio" +
                "n=\"WcfService.Entities.IllnessHasSymptom_Illness\"><End Role=\"IllnessHasSymptom_I" +
                "llness_Source\" EntitySet=\"TableIllnessHasSymptom\" /><End Role=\"IllnessHasSymptom" +
                "_Illness_Target\" EntitySet=\"TableIllness\" /></AssociationSe";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"t><AssociationSet Name=""IllnessHasSymptom_Symptom"" Association=""WcfService.Entities.IllnessHasSymptom_Symptom""><End Role=""IllnessHasSymptom_Symptom_Source"" EntitySet=""TableIllnessHasSymptom"" /><End Role=""IllnessHasSymptom_Symptom_Target"" EntitySet=""TableSymptom"" /></AssociationSet><AssociationSet Name=""LifeFuncMeasure_Patient"" Association=""WcfService.Entities.LifeFuncMeasure_Patient""><End Role=""LifeFuncMeasure_Patient_Source"" EntitySet=""TableLifeFuncMeasure"" /><End Role=""LifeFuncMeasure_Patient_Target"" EntitySet=""TablePatient"" /></AssociationSet><AssociationSet Name=""PatientWasSick_Illness"" Association=""WcfService.Entities.PatientWasSick_Illness""><End Role=""PatientWasSick_Illness_Source"" EntitySet=""TablePatientWasSick"" /><End Role=""PatientWasSick_Illness_Target"" EntitySet=""TableIllness"" /></AssociationSet><AssociationSet Name=""PatientWasSick_Patient"" Association=""WcfService.Entities.PatientWasSick_Patient""><End Role=""PatientWasSick_Patient_Source"" EntitySet=""TablePatientWasSick"" /><End Role=""PatientWasSick_Patient_Target"" EntitySet=""TablePatient"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.Illness in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Illness
    {
        /// <summary>
        /// Create a new Illness object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Illness CreateIllness(int ID)
        {
            Illness illness = new Illness();
            illness.Id = ID;
            return illness;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.IllnessHasSymptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IllnessHasSymptomId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IllnessHasSymptomId")]
    public partial class IllnessHasSymptom
    {
        /// <summary>
        /// Create a new IllnessHasSymptom object.
        /// </summary>
        /// <param name="illnessHasSymptomId">Initial value of IllnessHasSymptomId.</param>
        /// <param name="priority">Initial value of Priority.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        /// <param name="symptomId">Initial value of SymptomId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IllnessHasSymptom CreateIllnessHasSymptom(int illnessHasSymptomId, int priority, int illnessId, int symptomId)
        {
            IllnessHasSymptom illnessHasSymptom = new IllnessHasSymptom();
            illnessHasSymptom.IllnessHasSymptomId = illnessHasSymptomId;
            illnessHasSymptom.Priority = priority;
            illnessHasSymptom.IllnessId = illnessId;
            illnessHasSymptom.SymptomId = symptomId;
            return illnessHasSymptom;
        }
        /// <summary>
        /// There are no comments for Property IllnessHasSymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessHasSymptomId
        {
            get
            {
                return this._IllnessHasSymptomId;
            }
            set
            {
                this.OnIllnessHasSymptomIdChanging(value);
                this._IllnessHasSymptomId = value;
                this.OnIllnessHasSymptomIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessHasSymptomId;
        partial void OnIllnessHasSymptomIdChanging(int value);
        partial void OnIllnessHasSymptomIdChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Priority;
        partial void OnPriorityChanging(int value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Property SymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SymptomId
        {
            get
            {
                return this._SymptomId;
            }
            set
            {
                this.OnSymptomIdChanging(value);
                this._SymptomId = value;
                this.OnSymptomIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SymptomId;
        partial void OnSymptomIdChanging(int value);
        partial void OnSymptomIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Symptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Symptom Symptom
        {
            get
            {
                return this._Symptom;
            }
            set
            {
                this._Symptom = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Symptom _Symptom;
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.Symptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Symptom
    {
        /// <summary>
        /// Create a new Symptom object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Symptom CreateSymptom(int ID)
        {
            Symptom symptom = new Symptom();
            symptom.Id = ID;
            return symptom;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.LifeFuncMeasure in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LifeFuncMeasure
    {
        /// <summary>
        /// Create a new LifeFuncMeasure object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="temp">Initial value of Temp.</param>
        /// <param name="lowPressure">Initial value of LowPressure.</param>
        /// <param name="highPressure">Initial value of HighPressure.</param>
        /// <param name="pulse">Initial value of Pulse.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LifeFuncMeasure CreateLifeFuncMeasure(int ID, double temp, int lowPressure, int highPressure, int pulse, int patientId)
        {
            LifeFuncMeasure lifeFuncMeasure = new LifeFuncMeasure();
            lifeFuncMeasure.Id = ID;
            lifeFuncMeasure.Temp = temp;
            lifeFuncMeasure.LowPressure = lowPressure;
            lifeFuncMeasure.HighPressure = highPressure;
            lifeFuncMeasure.Pulse = pulse;
            lifeFuncMeasure.PatientId = patientId;
            return lifeFuncMeasure;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Temp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Temp
        {
            get
            {
                return this._Temp;
            }
            set
            {
                this.OnTempChanging(value);
                this._Temp = value;
                this.OnTempChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Temp;
        partial void OnTempChanging(double value);
        partial void OnTempChanged();
        /// <summary>
        /// There are no comments for Property LowPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LowPressure
        {
            get
            {
                return this._LowPressure;
            }
            set
            {
                this.OnLowPressureChanging(value);
                this._LowPressure = value;
                this.OnLowPressureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LowPressure;
        partial void OnLowPressureChanging(int value);
        partial void OnLowPressureChanged();
        /// <summary>
        /// There are no comments for Property HighPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int HighPressure
        {
            get
            {
                return this._HighPressure;
            }
            set
            {
                this.OnHighPressureChanging(value);
                this._HighPressure = value;
                this.OnHighPressureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _HighPressure;
        partial void OnHighPressureChanging(int value);
        partial void OnHighPressureChanged();
        /// <summary>
        /// There are no comments for Property Pulse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Pulse
        {
            get
            {
                return this._Pulse;
            }
            set
            {
                this.OnPulseChanging(value);
                this._Pulse = value;
                this.OnPulseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Pulse;
        partial void OnPulseChanging(int value);
        partial void OnPulseChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Patient
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="sex">Initial value of Sex.</param>
        /// <param name="height">Initial value of Height.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Patient CreatePatient(int ID, bool sex, int height)
        {
            Patient patient = new Patient();
            patient.Id = ID;
            patient.Sex = sex;
            patient.Height = height;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FstName
        {
            get
            {
                return this._FstName;
            }
            set
            {
                this.OnFstNameChanging(value);
                this._FstName = value;
                this.OnFstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FstName;
        partial void OnFstNameChanging(string value);
        partial void OnFstNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                this._Sex = value;
                this.OnSexChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Sex;
        partial void OnSexChanging(bool value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Height;
        partial void OnHeightChanging(int value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Pass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Pass
        {
            get
            {
                if ((this._Pass != null))
                {
                    return ((byte[])(this._Pass.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPassChanging(value);
                this._Pass = value;
                this.OnPassChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Pass;
        partial void OnPassChanging(byte[] value);
        partial void OnPassChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.Entities.PatientWasSick in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PatientWasSick
    {
        /// <summary>
        /// Create a new PatientWasSick object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PatientWasSick CreatePatientWasSick(int ID, global::System.DateTime date, int patientId, int illnessId)
        {
            PatientWasSick patientWasSick = new PatientWasSick();
            patientWasSick.Id = ID;
            patientWasSick.Date = date;
            patientWasSick.PatientId = patientId;
            patientWasSick.IllnessId = illnessId;
            return patientWasSick;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
    }
}
