//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 06.11.2016 22:24:48
namespace MediApp.DbServices
{
    
    /// <summary>
    /// There are no comments for PatientsContext in the schema.
    /// </summary>
    public partial class PatientsContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PatientsContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PatientsContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WcfService.DbContext", "MediApp.DbServices");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MediApp.DbServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WcfService.DbContext.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Illness> TableIllness
        {
            get
            {
                if ((this._TableIllness == null))
                {
                    this._TableIllness = base.CreateQuery<Illness>("TableIllness");
                }
                return this._TableIllness;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Illness> _TableIllness;
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> TableIllnessHasSymptom
        {
            get
            {
                if ((this._TableIllnessHasSymptom == null))
                {
                    this._TableIllnessHasSymptom = base.CreateQuery<IllnessHasSymptom>("TableIllnessHasSymptom");
                }
                return this._TableIllnessHasSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> _TableIllnessHasSymptom;
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Symptom> TableSymptom
        {
            get
            {
                if ((this._TableSymptom == null))
                {
                    this._TableSymptom = base.CreateQuery<Symptom>("TableSymptom");
                }
                return this._TableSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Symptom> _TableSymptom;
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> TableLifeFuncMeasure
        {
            get
            {
                if ((this._TableLifeFuncMeasure == null))
                {
                    this._TableLifeFuncMeasure = base.CreateQuery<LifeFuncMeasure>("TableLifeFuncMeasure");
                }
                return this._TableLifeFuncMeasure;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> _TableLifeFuncMeasure;
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Patient> TablePatient
        {
            get
            {
                if ((this._TablePatient == null))
                {
                    this._TablePatient = base.CreateQuery<Patient>("TablePatient");
                }
                return this._TablePatient;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Patient> _TablePatient;
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> TablePatientWasSick
        {
            get
            {
                if ((this._TablePatientWasSick == null))
                {
                    this._TablePatientWasSick = base.CreateQuery<PatientWasSick>("TablePatientWasSick");
                }
                return this._TablePatientWasSick;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> _TablePatientWasSick;
        /// <summary>
        /// There are no comments for TableRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Role> TableRole
        {
            get
            {
                if ((this._TableRole == null))
                {
                    this._TableRole = base.CreateQuery<Role>("TableRole");
                }
                return this._TableRole;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Role> _TableRole;
        /// <summary>
        /// There are no comments for TableUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> TableUser
        {
            get
            {
                if ((this._TableUser == null))
                {
                    this._TableUser = base.CreateQuery<User>("TableUser");
                }
                return this._TableUser;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _TableUser;
        /// <summary>
        /// There are no comments for TableUserHasRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserHasRole> TableUserHasRole
        {
            get
            {
                if ((this._TableUserHasRole == null))
                {
                    this._TableUserHasRole = base.CreateQuery<UserHasRole>("TableUserHasRole");
                }
                return this._TableUserHasRole;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserHasRole> _TableUserHasRole;
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllness(Illness illness)
        {
            base.AddObject("TableIllness", illness);
        }
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllnessHasSymptom(IllnessHasSymptom illnessHasSymptom)
        {
            base.AddObject("TableIllnessHasSymptom", illnessHasSymptom);
        }
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableSymptom(Symptom symptom)
        {
            base.AddObject("TableSymptom", symptom);
        }
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableLifeFuncMeasure(LifeFuncMeasure lifeFuncMeasure)
        {
            base.AddObject("TableLifeFuncMeasure", lifeFuncMeasure);
        }
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatient(Patient patient)
        {
            base.AddObject("TablePatient", patient);
        }
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatientWasSick(PatientWasSick patientWasSick)
        {
            base.AddObject("TablePatientWasSick", patientWasSick);
        }
        /// <summary>
        /// There are no comments for TableRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableRole(Role role)
        {
            base.AddObject("TableRole", role);
        }
        /// <summary>
        /// There are no comments for TableUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableUser(User user)
        {
            base.AddObject("TableUser", user);
        }
        /// <summary>
        /// There are no comments for TableUserHasRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableUserHasRole(UserHasRole userHasRole)
        {
            base.AddObject("TableUserHasRole", userHasRole);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WcfService.DbContext\" xmlns=\"http://schemas.microsoft.com/ado/2009/11" +
                "/edm\"><EntityType Name=\"Illness\"><Key><PropertyRef Name=\"Id\" /></Key><Property N" +
                "ame=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" x" +
                "mlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Na" +
                "me=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /" +
                "></EntityType><EntityType Name=\"IllnessHasSymptom\"><Key><PropertyRef Name=\"Illne" +
                "ssHasSymptomId\" /></Key><Property Name=\"IllnessHasSymptomId\" Type=\"Edm.Int32\" Nu" +
                "llable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.micr" +
                "osoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Priority\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"SymptomId\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationP" +
                "roperty Name=\"Illness\" Relationship=\"WcfService.DbContext.IllnessHasSymptom_Illn" +
                "ess\" ToRole=\"IllnessHasSymptom_Illness_Target\" FromRole=\"IllnessHasSymptom_Illne" +
                "ss_Source\" /><NavigationProperty Name=\"Symptom\" Relationship=\"WcfService.DbConte" +
                "xt.IllnessHasSymptom_Symptom\" ToRole=\"IllnessHasSymptom_Symptom_Target\" FromRole" +
                "=\"IllnessHasSymptom_Symptom_Source\" /></EntityType><EntityType Name=\"Symptom\"><K" +
                "ey><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.c" +
                "om/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLeng" +
                "th=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><EntityType Name=\"Lif" +
                "eFuncMeasure\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://sch" +
                "emas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Temp\" Type=\"Edm" +
                ".Double\" Nullable=\"false\" /><Property Name=\"LowPressure\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"HighPressure\" Type=\"Edm.Int32\" Nullable=\"false\" /><" +
                "Property Name=\"Pulse\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Patien" +
                "tId\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Patient\" Rela" +
                "tionship=\"WcfService.DbContext.LifeFuncMeasure_Patient\" ToRole=\"LifeFuncMeasure_" +
                "Patient_Target\" FromRole=\"LifeFuncMeasure_Patient_Source\" /></EntityType><Entity" +
                "Type Name=\"Patient\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Pesel\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Sex\" Type=\"Edm.Boolean\" Nullab" +
                "le=\"false\" /><Property Name=\"Height\" Type=\"Edm.Int32\" Nullable=\"false\" /></Entit" +
                "yType><EntityType Name=\"PatientWasSick\"><Key><PropertyRef Name=\"Id\" /></Key><Pro" +
                "perty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Iden" +
                "tity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Prop" +
                "erty Name=\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"PatientI" +
                "d\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><NavigationProperty Name=\"Illness\" Relationship=\"WcfServic" +
                "e.DbContext.PatientWasSick_Illness\" ToRole=\"PatientWasSick_Illness_Target\" FromR" +
                "ole=\"PatientWasSick_Illness_Source\" /><NavigationProperty Name=\"Patient\" Relatio" +
                "nship=\"WcfService.DbContext.PatientWasSick_Patient\" ToRole=\"PatientWasSick_Patie" +
                "nt_Target\" FromRole=\"PatientWasSick_Patient_Source\" /></EntityType><EntityType N" +
                "ame=\"Role\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schema" +
                "s.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.St" +
                "ring\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><EntityT" +
                "ype Name=\"User\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://s" +
                "chemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"FstName\" Type" +
                "=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Nam" +
                "e=\"Surname\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\"" +
                " /><Property Name=\"Pesel\" Type=\"Edm.Int32\" /><Property Name=\"Email\" Type=\"Edm.St" +
                "ring\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Pass\"" +
                " Type=\"Edm.Binary\" MaxLength=\"Max\" FixedLength=\"false\" /></EntityType><EntityTyp" +
                "e Name=\"UserHasRole\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"htt" +
                "p://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"UserId\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"RoleId\" Type=\"Edm.Int32\" Nul" +
                "lable=\"false\" /><NavigationProperty Name=\"Role\" Relationship=\"WcfService.DbConte" +
                "xt.UserHasRole_Role\" ToRole=\"UserHasRole_Role_Target\" FromRole=\"UserHasRole_Role" +
                "_Source\" /><NavigationProperty Name=\"User\" Relationship=\"WcfService.DbContext.Us" +
                "erHasRole_User\" ToRole=\"UserHasRole_User_Target\" FromRole=\"UserHasRole_User_Sour" +
                "ce\" /></EntityType><Association Name=\"IllnessHasSymptom_Illness\"><End Type=\"WcfS" +
                "ervice.DbContext.Illness\" Role=\"IllnessHasSymptom_Illness_Target\" Multiplicity=\"" +
                "1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfService.DbContext.IllnessHas" +
                "Symptom\" Role=\"IllnessHasSymptom_Illness_Source\" Multiplicity=\"*\" /><Referential" +
                "Constraint><Principal Role=\"IllnessHasSymptom_Illness_Target\"><PropertyRef Name=" +
                "\"Id\" /></Principal><Dependent Role=\"IllnessHasSymptom_Illness_Source\"><PropertyR" +
                "ef Name=\"IllnessId\" /></Dependent></ReferentialConstraint></Association><Associa" +
                "tion Name=\"IllnessHasSymptom_Symptom\"><End Type=\"WcfService.DbContext.Symptom\" R" +
                "ole=\"IllnessHasSymptom_Symptom_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascad" +
                "e\" /></End><End Type=\"WcfService.DbContext.IllnessHasSymptom\" Role=\"IllnessHasSy" +
                "mptom_Symptom_Source\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=" +
                "\"IllnessHasSymptom_Symptom_Target\"><PropertyRef Name=\"Id\" /></Principal><Depende" +
                "nt Role=\"IllnessHasSymptom_Symptom_Source\"><PropertyRef Name=\"SymptomId\" /></Dep" +
                "endent></ReferentialConstraint></Association><Association Name=\"LifeFuncMeasure_" +
                "Patient\"><End Type=\"WcfService.DbContext.Patient\" Role=\"LifeFuncMeasure_Patient_" +
                "Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfServic" +
                "e.DbContext.LifeFuncMeasure\" Role=\"LifeFuncMeasure_Patient_Source\" Multiplicity=" +
                "\"*\" /><ReferentialConstraint><Principal Role=\"LifeFuncMeasure_Patient_Target\"><P" +
                "ropertyRef Name=\"Id\" /></Principal><Dependent Role=\"LifeFuncMeasure_Patient_Sour" +
                "ce\"><PropertyRef Name=\"PatientId\" /></Dependent></ReferentialConstraint></Associ" +
                "ation><Association Name=\"PatientWasSick_Illness\"><End Type=\"WcfService.DbContext" +
                ".Illness\" Role=\"PatientWasSick_Illness_Target\" Multiplicity=\"1\"><OnDelete Action" +
                "=\"Cascade\" /></End><End Type=\"WcfService.DbContext.PatientWasSick\" Role=\"Patient" +
                "WasSick_Illness_Source\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Rol" +
                "e=\"PatientWasSick_Illness_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependen" +
                "t Role=\"PatientWasSick_Illness_Source\"><PropertyRef Name=\"IllnessId\" /></Depende" +
                "nt></ReferentialConstraint></Association><Association Name=";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "\"PatientWasSick_Patient\"><End Type=\"WcfService.DbContext.Patient\" Role=\"PatientWa" +
                "sSick_Patient_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End T" +
                "ype=\"WcfService.DbContext.PatientWasSick\" Role=\"PatientWasSick_Patient_Source\" M" +
                "ultiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"PatientWasSick_Patient" +
                "_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"PatientWasSick_Pa" +
                "tient_Source\"><PropertyRef Name=\"PatientId\" /></Dependent></ReferentialConstrain" +
                "t></Association><Association Name=\"UserHasRole_Role\"><End Type=\"WcfService.DbCon" +
                "text.Role\" Role=\"UserHasRole_Role_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cas" +
                "cade\" /></End><End Type=\"WcfService.DbContext.UserHasRole\" Role=\"UserHasRole_Rol" +
                "e_Source\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"UserHasRole" +
                "_Role_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"UserHasRole_" +
                "Role_Source\"><PropertyRef Name=\"RoleId\" /></Dependent></ReferentialConstraint></" +
                "Association><Association Name=\"UserHasRole_User\"><End Type=\"WcfService.DbContext" +
                ".User\" Role=\"UserHasRole_User_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade" +
                "\" /></End><End Type=\"WcfService.DbContext.UserHasRole\" Role=\"UserHasRole_User_So" +
                "urce\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"UserHasRole_Use" +
                "r_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"UserHasRole_User" +
                "_Source\"><PropertyRef Name=\"UserId\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation><EntityContainer Name=\"PatientsContext\" m:IsDefaultEntityContainer=\"true" +
                "\"><EntitySet Name=\"TableIllness\" EntityType=\"WcfService.DbContext.Illness\" /><En" +
                "titySet Name=\"TableIllnessHasSymptom\" EntityType=\"WcfService.DbContext.IllnessHa" +
                "sSymptom\" /><EntitySet Name=\"TableSymptom\" EntityType=\"WcfService.DbContext.Symp" +
                "tom\" /><EntitySet Name=\"TableLifeFuncMeasure\" EntityType=\"WcfService.DbContext.L" +
                "ifeFuncMeasure\" /><EntitySet Name=\"TablePatient\" EntityType=\"WcfService.DbContex" +
                "t.Patient\" /><EntitySet Name=\"TablePatientWasSick\" EntityType=\"WcfService.DbCont" +
                "ext.PatientWasSick\" /><EntitySet Name=\"TableRole\" EntityType=\"WcfService.DbConte" +
                "xt.Role\" /><EntitySet Name=\"TableUser\" EntityType=\"WcfService.DbContext.User\" />" +
                "<EntitySet Name=\"TableUserHasRole\" EntityType=\"WcfService.DbContext.UserHasRole\"" +
                " /><FunctionImport Name=\"GetIllness\" ReturnType=\"Collection(WcfService.DbContext" +
                ".Illness)\" EntitySet=\"TableIllness\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"f" +
                "ill\" m:HttpMethod=\"GET\" /><AssociationSet Name=\"IllnessHasSymptom_Illness\" Assoc" +
                "iation=\"WcfService.DbContext.IllnessHasSymptom_Illness\"><End Role=\"IllnessHasSym" +
                "ptom_Illness_Source\" EntitySet=\"TableIllnessHasSymptom\" /><End Role=\"IllnessHasS" +
                "ymptom_Illness_Target\" EntitySet=\"TableIllness\" /></AssociationSet><AssociationS" +
                "et Name=\"IllnessHasSymptom_Symptom\" Association=\"WcfService.DbContext.IllnessHas" +
                "Symptom_Symptom\"><End Role=\"IllnessHasSymptom_Symptom_Source\" EntitySet=\"TableIl" +
                "lnessHasSymptom\" /><End Role=\"IllnessHasSymptom_Symptom_Target\" EntitySet=\"Table" +
                "Symptom\" /></AssociationSet><AssociationSet Name=\"LifeFuncMeasure_Patient\" Assoc" +
                "iation=\"WcfService.DbContext.LifeFuncMeasure_Patient\"><End Role=\"LifeFuncMeasure" +
                "_Patient_Source\" EntitySet=\"TableLifeFuncMeasure\" /><End Role=\"LifeFuncMeasure_P" +
                "atient_Target\" EntitySet=\"TablePatient\" /></AssociationSet><AssociationSet Name=" +
                "\"PatientWasSick_Illness\" Association=\"WcfService.DbContext.PatientWasSick_Illnes" +
                "s\"><End Role=\"PatientWasSick_Illness_Source\" EntitySet=\"TablePatientWasSick\" /><" +
                "End Role=\"PatientWasSick_Illness_Target\" EntitySet=\"TableIllness\" /></Associatio" +
                "nSet><AssociationSet Name=\"PatientWasSick_Patient\" Association=\"WcfService.DbCon" +
                "text.PatientWasSick_Patient\"><End Role=\"PatientWasSick_Patient_Source\" EntitySet" +
                "=\"TablePatientWasSick\" /><End Role=\"PatientWasSick_Patient_Target\" EntitySet=\"Ta" +
                "blePatient\" /></AssociationSet><AssociationSet Name=\"UserHasRole_Role\" Associati" +
                "on=\"WcfService.DbContext.UserHasRole_Role\"><End Role=\"UserHasRole_Role_Source\" E" +
                "ntitySet=\"TableUserHasRole\" /><End Role=\"UserHasRole_Role_Target\" EntitySet=\"Tab" +
                "leRole\" /></AssociationSet><AssociationSet Name=\"UserHasRole_User\" Association=\"" +
                "WcfService.DbContext.UserHasRole_User\"><End Role=\"UserHasRole_User_Source\" Entit" +
                "ySet=\"TableUserHasRole\" /><End Role=\"UserHasRole_User_Target\" EntitySet=\"TableUs" +
                "er\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edm" +
                "x>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Illness in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Illness
    {
        /// <summary>
        /// Create a new Illness object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Illness CreateIllness(int ID)
        {
            Illness illness = new Illness();
            illness.Id = ID;
            return illness;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.IllnessHasSymptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IllnessHasSymptomId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IllnessHasSymptomId")]
    public partial class IllnessHasSymptom
    {
        /// <summary>
        /// Create a new IllnessHasSymptom object.
        /// </summary>
        /// <param name="illnessHasSymptomId">Initial value of IllnessHasSymptomId.</param>
        /// <param name="priority">Initial value of Priority.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        /// <param name="symptomId">Initial value of SymptomId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IllnessHasSymptom CreateIllnessHasSymptom(int illnessHasSymptomId, int priority, int illnessId, int symptomId)
        {
            IllnessHasSymptom illnessHasSymptom = new IllnessHasSymptom();
            illnessHasSymptom.IllnessHasSymptomId = illnessHasSymptomId;
            illnessHasSymptom.Priority = priority;
            illnessHasSymptom.IllnessId = illnessId;
            illnessHasSymptom.SymptomId = symptomId;
            return illnessHasSymptom;
        }
        /// <summary>
        /// There are no comments for Property IllnessHasSymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessHasSymptomId
        {
            get
            {
                return this._IllnessHasSymptomId;
            }
            set
            {
                this.OnIllnessHasSymptomIdChanging(value);
                this._IllnessHasSymptomId = value;
                this.OnIllnessHasSymptomIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessHasSymptomId;
        partial void OnIllnessHasSymptomIdChanging(int value);
        partial void OnIllnessHasSymptomIdChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Priority;
        partial void OnPriorityChanging(int value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Property SymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SymptomId
        {
            get
            {
                return this._SymptomId;
            }
            set
            {
                this.OnSymptomIdChanging(value);
                this._SymptomId = value;
                this.OnSymptomIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SymptomId;
        partial void OnSymptomIdChanging(int value);
        partial void OnSymptomIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Symptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Symptom Symptom
        {
            get
            {
                return this._Symptom;
            }
            set
            {
                this._Symptom = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Symptom _Symptom;
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Symptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Symptom
    {
        /// <summary>
        /// Create a new Symptom object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Symptom CreateSymptom(int ID)
        {
            Symptom symptom = new Symptom();
            symptom.Id = ID;
            return symptom;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.LifeFuncMeasure in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LifeFuncMeasure
    {
        /// <summary>
        /// Create a new LifeFuncMeasure object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="temp">Initial value of Temp.</param>
        /// <param name="lowPressure">Initial value of LowPressure.</param>
        /// <param name="highPressure">Initial value of HighPressure.</param>
        /// <param name="pulse">Initial value of Pulse.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LifeFuncMeasure CreateLifeFuncMeasure(int ID, double temp, int lowPressure, int highPressure, int pulse, int patientId)
        {
            LifeFuncMeasure lifeFuncMeasure = new LifeFuncMeasure();
            lifeFuncMeasure.Id = ID;
            lifeFuncMeasure.Temp = temp;
            lifeFuncMeasure.LowPressure = lowPressure;
            lifeFuncMeasure.HighPressure = highPressure;
            lifeFuncMeasure.Pulse = pulse;
            lifeFuncMeasure.PatientId = patientId;
            return lifeFuncMeasure;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Temp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Temp
        {
            get
            {
                return this._Temp;
            }
            set
            {
                this.OnTempChanging(value);
                this._Temp = value;
                this.OnTempChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Temp;
        partial void OnTempChanging(double value);
        partial void OnTempChanged();
        /// <summary>
        /// There are no comments for Property LowPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LowPressure
        {
            get
            {
                return this._LowPressure;
            }
            set
            {
                this.OnLowPressureChanging(value);
                this._LowPressure = value;
                this.OnLowPressureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LowPressure;
        partial void OnLowPressureChanging(int value);
        partial void OnLowPressureChanged();
        /// <summary>
        /// There are no comments for Property HighPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int HighPressure
        {
            get
            {
                return this._HighPressure;
            }
            set
            {
                this.OnHighPressureChanging(value);
                this._HighPressure = value;
                this.OnHighPressureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _HighPressure;
        partial void OnHighPressureChanging(int value);
        partial void OnHighPressureChanged();
        /// <summary>
        /// There are no comments for Property Pulse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Pulse
        {
            get
            {
                return this._Pulse;
            }
            set
            {
                this.OnPulseChanging(value);
                this._Pulse = value;
                this.OnPulseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Pulse;
        partial void OnPulseChanging(int value);
        partial void OnPulseChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Patient
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="pesel">Initial value of Pesel.</param>
        /// <param name="sex">Initial value of Sex.</param>
        /// <param name="height">Initial value of Height.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Patient CreatePatient(int ID, int pesel, bool sex, int height)
        {
            Patient patient = new Patient();
            patient.Id = ID;
            patient.Pesel = pesel;
            patient.Sex = sex;
            patient.Height = height;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Pesel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Pesel
        {
            get
            {
                return this._Pesel;
            }
            set
            {
                this.OnPeselChanging(value);
                this._Pesel = value;
                this.OnPeselChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Pesel;
        partial void OnPeselChanging(int value);
        partial void OnPeselChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                this._Sex = value;
                this.OnSexChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Sex;
        partial void OnSexChanging(bool value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Height;
        partial void OnHeightChanging(int value);
        partial void OnHeightChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.PatientWasSick in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PatientWasSick
    {
        /// <summary>
        /// Create a new PatientWasSick object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PatientWasSick CreatePatientWasSick(int ID, global::System.DateTime date, int patientId, int illnessId)
        {
            PatientWasSick patientWasSick = new PatientWasSick();
            patientWasSick.Id = ID;
            patientWasSick.Date = date;
            patientWasSick.PatientId = patientId;
            patientWasSick.IllnessId = illnessId;
            return patientWasSick;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Role
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Role CreateRole(int ID)
        {
            Role role = new Role();
            role.Id = ID;
            return role;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID)
        {
            User user = new User();
            user.Id = ID;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FstName
        {
            get
            {
                return this._FstName;
            }
            set
            {
                this.OnFstNameChanging(value);
                this._FstName = value;
                this.OnFstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FstName;
        partial void OnFstNameChanging(string value);
        partial void OnFstNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Pesel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Pesel
        {
            get
            {
                return this._Pesel;
            }
            set
            {
                this.OnPeselChanging(value);
                this._Pesel = value;
                this.OnPeselChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Pesel;
        partial void OnPeselChanging(global::System.Nullable<int> value);
        partial void OnPeselChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Pass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Pass
        {
            get
            {
                if ((this._Pass != null))
                {
                    return ((byte[])(this._Pass.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPassChanging(value);
                this._Pass = value;
                this.OnPassChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Pass;
        partial void OnPassChanging(byte[] value);
        partial void OnPassChanged();
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.UserHasRole in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UserHasRole
    {
        /// <summary>
        /// Create a new UserHasRole object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="roleId">Initial value of RoleId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserHasRole CreateUserHasRole(int ID, int userId, int roleId)
        {
            UserHasRole userHasRole = new UserHasRole();
            userHasRole.Id = ID;
            userHasRole.UserId = userId;
            userHasRole.RoleId = roleId;
            return userHasRole;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property RoleId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this._RoleId = value;
                this.OnRoleIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RoleId;
        partial void OnRoleIdChanging(int value);
        partial void OnRoleIdChanged();
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Role Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this._Role = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Role _Role;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
    }
}
