//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 05.12.2016 15:59:02
namespace WpfMediApp.DbServices
{
    
    /// <summary>
    /// There are no comments for PatientsContext in the schema.
    /// </summary>
    public partial class PatientsContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PatientsContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PatientsContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WcfService.DbContext", "WpfMediApp.DbServices");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WpfMediApp.DbServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WcfService.DbContext.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Illness> TableIllness
        {
            get
            {
                if ((this._TableIllness == null))
                {
                    this._TableIllness = base.CreateQuery<Illness>("TableIllness");
                }
                return this._TableIllness;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Illness> _TableIllness;
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> TableIllnessHasSymptom
        {
            get
            {
                if ((this._TableIllnessHasSymptom == null))
                {
                    this._TableIllnessHasSymptom = base.CreateQuery<IllnessHasSymptom>("TableIllnessHasSymptom");
                }
                return this._TableIllnessHasSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<IllnessHasSymptom> _TableIllnessHasSymptom;
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Symptom> TableSymptom
        {
            get
            {
                if ((this._TableSymptom == null))
                {
                    this._TableSymptom = base.CreateQuery<Symptom>("TableSymptom");
                }
                return this._TableSymptom;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Symptom> _TableSymptom;
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> TableLifeFuncMeasure
        {
            get
            {
                if ((this._TableLifeFuncMeasure == null))
                {
                    this._TableLifeFuncMeasure = base.CreateQuery<LifeFuncMeasure>("TableLifeFuncMeasure");
                }
                return this._TableLifeFuncMeasure;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LifeFuncMeasure> _TableLifeFuncMeasure;
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Patient> TablePatient
        {
            get
            {
                if ((this._TablePatient == null))
                {
                    this._TablePatient = base.CreateQuery<Patient>("TablePatient");
                }
                return this._TablePatient;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Patient> _TablePatient;
        /// <summary>
        /// There are no comments for TableOutput in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Output> TableOutput
        {
            get
            {
                if ((this._TableOutput == null))
                {
                    this._TableOutput = base.CreateQuery<Output>("TableOutput");
                }
                return this._TableOutput;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Output> _TableOutput;
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> TablePatientWasSick
        {
            get
            {
                if ((this._TablePatientWasSick == null))
                {
                    this._TablePatientWasSick = base.CreateQuery<PatientWasSick>("TablePatientWasSick");
                }
                return this._TablePatientWasSick;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PatientWasSick> _TablePatientWasSick;
        /// <summary>
        /// There are no comments for TableQuestion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Question> TableQuestion
        {
            get
            {
                if ((this._TableQuestion == null))
                {
                    this._TableQuestion = base.CreateQuery<Question>("TableQuestion");
                }
                return this._TableQuestion;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Question> _TableQuestion;
        /// <summary>
        /// There are no comments for TableRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Role> TableRole
        {
            get
            {
                if ((this._TableRole == null))
                {
                    this._TableRole = base.CreateQuery<Role>("TableRole");
                }
                return this._TableRole;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Role> _TableRole;
        /// <summary>
        /// There are no comments for TableUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> TableUser
        {
            get
            {
                if ((this._TableUser == null))
                {
                    this._TableUser = base.CreateQuery<User>("TableUser");
                }
                return this._TableUser;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _TableUser;
        /// <summary>
        /// There are no comments for TableIllness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllness(Illness illness)
        {
            base.AddObject("TableIllness", illness);
        }
        /// <summary>
        /// There are no comments for TableIllnessHasSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableIllnessHasSymptom(IllnessHasSymptom illnessHasSymptom)
        {
            base.AddObject("TableIllnessHasSymptom", illnessHasSymptom);
        }
        /// <summary>
        /// There are no comments for TableSymptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableSymptom(Symptom symptom)
        {
            base.AddObject("TableSymptom", symptom);
        }
        /// <summary>
        /// There are no comments for TableLifeFuncMeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableLifeFuncMeasure(LifeFuncMeasure lifeFuncMeasure)
        {
            base.AddObject("TableLifeFuncMeasure", lifeFuncMeasure);
        }
        /// <summary>
        /// There are no comments for TablePatient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatient(Patient patient)
        {
            base.AddObject("TablePatient", patient);
        }
        /// <summary>
        /// There are no comments for TableOutput in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableOutput(Output output)
        {
            base.AddObject("TableOutput", output);
        }
        /// <summary>
        /// There are no comments for TablePatientWasSick in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTablePatientWasSick(PatientWasSick patientWasSick)
        {
            base.AddObject("TablePatientWasSick", patientWasSick);
        }
        /// <summary>
        /// There are no comments for TableQuestion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableQuestion(Question question)
        {
            base.AddObject("TableQuestion", question);
        }
        /// <summary>
        /// There are no comments for TableRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableRole(Role role)
        {
            base.AddObject("TableRole", role);
        }
        /// <summary>
        /// There are no comments for TableUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTableUser(User user)
        {
            base.AddObject("TableUser", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WcfService.DbContext\" xmlns=\"http://schemas.microsoft.com/ado/2009/11" +
                "/edm\"><EntityType Name=\"Illness\"><Key><PropertyRef Name=\"Id\" /></Key><Property N" +
                "ame=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" x" +
                "mlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Na" +
                "me=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /" +
                "><Property Name=\"Description\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" " +
                "/></EntityType><EntityType Name=\"IllnessHasSymptom\"><Key><PropertyRef Name=\"Illn" +
                "essHasSymptomId\" /></Key><Property Name=\"IllnessHasSymptomId\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.mic" +
                "rosoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Priority\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"SymptomId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Navigation" +
                "Property Name=\"Illness\" Relationship=\"WcfService.DbContext.IllnessHasSymptom_Ill" +
                "ness\" ToRole=\"IllnessHasSymptom_Illness_Target\" FromRole=\"IllnessHasSymptom_Illn" +
                "ess_Source\" /><NavigationProperty Name=\"Symptom\" Relationship=\"WcfService.DbCont" +
                "ext.IllnessHasSymptom_Symptom\" ToRole=\"IllnessHasSymptom_Symptom_Target\" FromRol" +
                "e=\"IllnessHasSymptom_Symptom_Source\" /></EntityType><EntityType Name=\"Symptom\"><" +
                "Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft." +
                "com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLen" +
                "gth=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><EntityType Name=\"Li" +
                "feFuncMeasure\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm" +
                ".Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://sc" +
                "hemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Temp\" Type=\"Ed" +
                "m.Double\" Nullable=\"false\" /><Property Name=\"LowPressure\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" /><Property Name=\"HighPressure\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<Property Name=\"Pulse\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Date\"" +
                " Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"PatientId\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><NavigationProperty Name=\"Patient\" Relationship=\"WcfServi" +
                "ce.DbContext.LifeFuncMeasure_Patient\" ToRole=\"LifeFuncMeasure_Patient_Target\" Fr" +
                "omRole=\"LifeFuncMeasure_Patient_Source\" /></EntityType><EntityType Name=\"Patient" +
                "\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microso" +
                "ft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Pesel\" Type=\"Edm.String\" Ma" +
                "xLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Sex\" Type=\"Ed" +
                "m.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"H" +
                "eight\" Type=\"Edm.Int32\" Nullable=\"false\" /></EntityType><EntityType Name=\"Output" +
                "\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microso" +
                "ft.com/ado/2009/02/edm/annotation\" /></EntityType><EntityType Name=\"PatientWasSi" +
                "ck\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nul" +
                "lable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.micro" +
                "soft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Date\" Type=\"Edm.DateTime\"" +
                " Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" MaxLength=\"Ma" +
                "x\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"PatientId\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"IllnessId\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><NavigationProperty Name=\"Illness\" Relationship=\"WcfService.DbContext.Pati" +
                "entWasSick_Illness\" ToRole=\"PatientWasSick_Illness_Target\" FromRole=\"PatientWasS" +
                "ick_Illness_Source\" /><NavigationProperty Name=\"Patient\" Relationship=\"WcfServic" +
                "e.DbContext.PatientWasSick_Patient\" ToRole=\"PatientWasSick_Patient_Target\" FromR" +
                "ole=\"PatientWasSick_Patient_Source\" /></EntityType><EntityType Name=\"Question\"><" +
                "Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft." +
                "com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLen" +
                "gth=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Content\" Type=\"Ed" +
                "m.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><Ent" +
                "ityType Name=\"Role\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http" +
                "://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Typ" +
                "e=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationP" +
                "roperty Name=\"Users\" Relationship=\"WcfService.DbContext.User_Roles\" ToRole=\"User" +
                "_Roles_Source\" FromRole=\"User_Roles_Target\" /></EntityType><EntityType Name=\"Use" +
                "r\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Null" +
                "able=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.micros" +
                "oft.com/ado/2009/02/edm/annotation\" /><Property Name=\"FstName\" Type=\"Edm.String\"" +
                " MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Surname\" T" +
                "ype=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"Pesel\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true" +
                "\" /><Property Name=\"Email\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\"" +
                " Unicode=\"true\" /><Property Name=\"Pass\" Type=\"Edm.Binary\" MaxLength=\"Max\" FixedL" +
                "ength=\"false\" /><NavigationProperty Name=\"Roles\" Relationship=\"WcfService.DbCont" +
                "ext.User_Roles\" ToRole=\"User_Roles_Target\" FromRole=\"User_Roles_Source\" /></Enti" +
                "tyType><Association Name=\"IllnessHasSymptom_Illness\"><End Type=\"WcfService.DbCon" +
                "text.Illness\" Role=\"IllnessHasSymptom_Illness_Target\" Multiplicity=\"1\"><OnDelete" +
                " Action=\"Cascade\" /></End><End Type=\"WcfService.DbContext.IllnessHasSymptom\" Rol" +
                "e=\"IllnessHasSymptom_Illness_Source\" Multiplicity=\"*\" /><ReferentialConstraint><" +
                "Principal Role=\"IllnessHasSymptom_Illness_Target\"><PropertyRef Name=\"Id\" /></Pri" +
                "ncipal><Dependent Role=\"IllnessHasSymptom_Illness_Source\"><PropertyRef Name=\"Ill" +
                "nessId\" /></Dependent></ReferentialConstraint></Association><Association Name=\"I" +
                "llnessHasSymptom_Symptom\"><End Type=\"WcfService.DbContext.Symptom\" Role=\"Illness" +
                "HasSymptom_Symptom_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><" +
                "End Type=\"WcfService.DbContext.IllnessHasSymptom\" Role=\"IllnessHasSymptom_Sympto" +
                "m_Source\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"IllnessHasS" +
                "ymptom_Symptom_Target\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Ill" +
                "nessHasSymptom_Symptom_Source\"><PropertyRef Name=\"SymptomId\" /></Dependent></Ref" +
                "erentialConstraint></Association><Association Name=\"LifeFuncMeasure_Patient\"><En" +
                "d Type=\"WcfService.DbContext.Patient\" Role=\"LifeFuncMeasure_Patient_Target\" Mult" +
                "iplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfService.DbContext." +
                "LifeFuncMeasure\" Role=\"LifeFuncMeasure_Patient_Source\" Multiplicity=\"*\" /><Refer" +
                "entialConstraint><Principal Role=\"LifeFuncMeasure_Patient_T";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "arget\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"LifeFuncMeasure_Pati" +
                "ent_Source\"><PropertyRef Name=\"PatientId\" /></Dependent></ReferentialConstraint>" +
                "</Association><Association Name=\"PatientWasSick_Illness\"><End Type=\"WcfService.D" +
                "bContext.Illness\" Role=\"PatientWasSick_Illness_Target\" Multiplicity=\"1\"><OnDelet" +
                "e Action=\"Cascade\" /></End><End Type=\"WcfService.DbContext.PatientWasSick\" Role=" +
                "\"PatientWasSick_Illness_Source\" Multiplicity=\"*\" /><ReferentialConstraint><Princ" +
                "ipal Role=\"PatientWasSick_Illness_Target\"><PropertyRef Name=\"Id\" /></Principal><" +
                "Dependent Role=\"PatientWasSick_Illness_Source\"><PropertyRef Name=\"IllnessId\" /><" +
                "/Dependent></ReferentialConstraint></Association><Association Name=\"PatientWasSi" +
                "ck_Patient\"><End Type=\"WcfService.DbContext.Patient\" Role=\"PatientWasSick_Patien" +
                "t_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"WcfServ" +
                "ice.DbContext.PatientWasSick\" Role=\"PatientWasSick_Patient_Source\" Multiplicity=" +
                "\"*\" /><ReferentialConstraint><Principal Role=\"PatientWasSick_Patient_Target\"><Pr" +
                "opertyRef Name=\"Id\" /></Principal><Dependent Role=\"PatientWasSick_Patient_Source" +
                "\"><PropertyRef Name=\"PatientId\" /></Dependent></ReferentialConstraint></Associat" +
                "ion><Association Name=\"User_Roles\"><End Type=\"WcfService.DbContext.User\" Role=\"U" +
                "ser_Roles_Source\" Multiplicity=\"*\" /><End Type=\"WcfService.DbContext.Role\" Role=" +
                "\"User_Roles_Target\" Multiplicity=\"*\" /></Association><EntityContainer Name=\"Pati" +
                "entsContext\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"TableIllness\" En" +
                "tityType=\"WcfService.DbContext.Illness\" /><EntitySet Name=\"TableIllnessHasSympto" +
                "m\" EntityType=\"WcfService.DbContext.IllnessHasSymptom\" /><EntitySet Name=\"TableS" +
                "ymptom\" EntityType=\"WcfService.DbContext.Symptom\" /><EntitySet Name=\"TableLifeFu" +
                "ncMeasure\" EntityType=\"WcfService.DbContext.LifeFuncMeasure\" /><EntitySet Name=\"" +
                "TablePatient\" EntityType=\"WcfService.DbContext.Patient\" /><EntitySet Name=\"Table" +
                "Output\" EntityType=\"WcfService.DbContext.Output\" /><EntitySet Name=\"TablePatient" +
                "WasSick\" EntityType=\"WcfService.DbContext.PatientWasSick\" /><EntitySet Name=\"Tab" +
                "leQuestion\" EntityType=\"WcfService.DbContext.Question\" /><EntitySet Name=\"TableR" +
                "ole\" EntityType=\"WcfService.DbContext.Role\" /><EntitySet Name=\"TableUser\" Entity" +
                "Type=\"WcfService.DbContext.User\" /><FunctionImport Name=\"GetUser\" ReturnType=\"Co" +
                "llection(WcfService.DbContext.User)\" EntitySet=\"TableUser\" m:HttpMethod=\"GET\"><P" +
                "arameter Name=\"email\" Type=\"Edm.String\" /></FunctionImport><FunctionImport Name=" +
                "\"GetPatient\" ReturnType=\"Collection(WcfService.DbContext.Patient)\" EntitySet=\"Ta" +
                "blePatient\" m:HttpMethod=\"GET\"><Parameter Name=\"pesel\" Type=\"Edm.String\" /></Fun" +
                "ctionImport><FunctionImport Name=\"GetRole\" ReturnType=\"Collection(WcfService.DbC" +
                "ontext.Role)\" EntitySet=\"TableRole\" m:HttpMethod=\"GET\"><Parameter Name=\"role\" Ty" +
                "pe=\"Edm.String\" /></FunctionImport><FunctionImport Name=\"GetUserRole\" ReturnType" +
                "=\"Collection(WcfService.DbContext.Role)\" EntitySet=\"TableRole\" m:HttpMethod=\"GET" +
                "\"><Parameter Name=\"userId\" Type=\"Edm.Int32\" Nullable=\"false\" /></FunctionImport>" +
                "<FunctionImport Name=\"GetPatientMeasures\" ReturnType=\"Collection(WcfService.DbCo" +
                "ntext.LifeFuncMeasure)\" EntitySet=\"TableLifeFuncMeasure\" m:HttpMethod=\"GET\"><Par" +
                "ameter Name=\"pesel\" Type=\"Edm.String\" /></FunctionImport><FunctionImport Name=\"G" +
                "etSymptom\" ReturnType=\"Collection(WcfService.DbContext.Symptom)\" EntitySet=\"Tabl" +
                "eSymptom\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"GetQuestion\" ReturnType=\"Co" +
                "llection(WcfService.DbContext.Question)\" EntitySet=\"TableQuestion\" m:HttpMethod=" +
                "\"GET\" /><FunctionImport Name=\"GetOutput\" ReturnType=\"Collection(WcfService.DbCon" +
                "text.Output)\" EntitySet=\"TableOutput\" m:HttpMethod=\"GET\" /><FunctionImport Name=" +
                "\"fill\" m:HttpMethod=\"GET\" /><AssociationSet Name=\"IllnessHasSymptom_Illness\" Ass" +
                "ociation=\"WcfService.DbContext.IllnessHasSymptom_Illness\"><End Role=\"IllnessHasS" +
                "ymptom_Illness_Source\" EntitySet=\"TableIllnessHasSymptom\" /><End Role=\"IllnessHa" +
                "sSymptom_Illness_Target\" EntitySet=\"TableIllness\" /></AssociationSet><Associatio" +
                "nSet Name=\"IllnessHasSymptom_Symptom\" Association=\"WcfService.DbContext.IllnessH" +
                "asSymptom_Symptom\"><End Role=\"IllnessHasSymptom_Symptom_Source\" EntitySet=\"Table" +
                "IllnessHasSymptom\" /><End Role=\"IllnessHasSymptom_Symptom_Target\" EntitySet=\"Tab" +
                "leSymptom\" /></AssociationSet><AssociationSet Name=\"LifeFuncMeasure_Patient\" Ass" +
                "ociation=\"WcfService.DbContext.LifeFuncMeasure_Patient\"><End Role=\"LifeFuncMeasu" +
                "re_Patient_Source\" EntitySet=\"TableLifeFuncMeasure\" /><End Role=\"LifeFuncMeasure" +
                "_Patient_Target\" EntitySet=\"TablePatient\" /></AssociationSet><AssociationSet Nam" +
                "e=\"PatientWasSick_Illness\" Association=\"WcfService.DbContext.PatientWasSick_Illn" +
                "ess\"><End Role=\"PatientWasSick_Illness_Source\" EntitySet=\"TablePatientWasSick\" /" +
                "><End Role=\"PatientWasSick_Illness_Target\" EntitySet=\"TableIllness\" /></Associat" +
                "ionSet><AssociationSet Name=\"PatientWasSick_Patient\" Association=\"WcfService.DbC" +
                "ontext.PatientWasSick_Patient\"><End Role=\"PatientWasSick_Patient_Source\" EntityS" +
                "et=\"TablePatientWasSick\" /><End Role=\"PatientWasSick_Patient_Target\" EntitySet=\"" +
                "TablePatient\" /></AssociationSet><AssociationSet Name=\"User_Roles\" Association=\"" +
                "WcfService.DbContext.User_Roles\"><End Role=\"User_Roles_Target\" EntitySet=\"TableR" +
                "ole\" /><End Role=\"User_Roles_Source\" EntitySet=\"TableUser\" /></AssociationSet></" +
                "EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Illness in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableIllness")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Illness : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Illness object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Illness CreateIllness(int ID, global::System.DateTime date)
        {
            Illness illness = new Illness();
            illness.Id = ID;
            illness.Date = date;
            return illness;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.IllnessHasSymptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IllnessHasSymptomId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableIllnessHasSymptom")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("IllnessHasSymptomId")]
    public partial class IllnessHasSymptom : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IllnessHasSymptom object.
        /// </summary>
        /// <param name="illnessHasSymptomId">Initial value of IllnessHasSymptomId.</param>
        /// <param name="priority">Initial value of Priority.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        /// <param name="symptomId">Initial value of SymptomId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IllnessHasSymptom CreateIllnessHasSymptom(int illnessHasSymptomId, int priority, int illnessId, int symptomId)
        {
            IllnessHasSymptom illnessHasSymptom = new IllnessHasSymptom();
            illnessHasSymptom.IllnessHasSymptomId = illnessHasSymptomId;
            illnessHasSymptom.Priority = priority;
            illnessHasSymptom.IllnessId = illnessId;
            illnessHasSymptom.SymptomId = symptomId;
            return illnessHasSymptom;
        }
        /// <summary>
        /// There are no comments for Property IllnessHasSymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessHasSymptomId
        {
            get
            {
                return this._IllnessHasSymptomId;
            }
            set
            {
                this.OnIllnessHasSymptomIdChanging(value);
                this._IllnessHasSymptomId = value;
                this.OnIllnessHasSymptomIdChanged();
                this.OnPropertyChanged("IllnessHasSymptomId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessHasSymptomId;
        partial void OnIllnessHasSymptomIdChanging(int value);
        partial void OnIllnessHasSymptomIdChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Priority;
        partial void OnPriorityChanging(int value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
                this.OnPropertyChanged("IllnessId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Property SymptomId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SymptomId
        {
            get
            {
                return this._SymptomId;
            }
            set
            {
                this.OnSymptomIdChanging(value);
                this._SymptomId = value;
                this.OnSymptomIdChanged();
                this.OnPropertyChanged("SymptomId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SymptomId;
        partial void OnSymptomIdChanging(int value);
        partial void OnSymptomIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
                this.OnPropertyChanged("Illness");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Symptom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Symptom Symptom
        {
            get
            {
                return this._Symptom;
            }
            set
            {
                this._Symptom = value;
                this.OnPropertyChanged("Symptom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Symptom _Symptom;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Symptom in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableSymptom")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Symptom : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Symptom object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Symptom CreateSymptom(int ID)
        {
            Symptom symptom = new Symptom();
            symptom.Id = ID;
            return symptom;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.LifeFuncMeasure in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableLifeFuncMeasure")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LifeFuncMeasure : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LifeFuncMeasure object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="temp">Initial value of Temp.</param>
        /// <param name="lowPressure">Initial value of LowPressure.</param>
        /// <param name="highPressure">Initial value of HighPressure.</param>
        /// <param name="pulse">Initial value of Pulse.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LifeFuncMeasure CreateLifeFuncMeasure(int ID, double temp, int lowPressure, int highPressure, int pulse, global::System.DateTime date, int patientId)
        {
            LifeFuncMeasure lifeFuncMeasure = new LifeFuncMeasure();
            lifeFuncMeasure.Id = ID;
            lifeFuncMeasure.Temp = temp;
            lifeFuncMeasure.LowPressure = lowPressure;
            lifeFuncMeasure.HighPressure = highPressure;
            lifeFuncMeasure.Pulse = pulse;
            lifeFuncMeasure.Date = date;
            lifeFuncMeasure.PatientId = patientId;
            return lifeFuncMeasure;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Temp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Temp
        {
            get
            {
                return this._Temp;
            }
            set
            {
                this.OnTempChanging(value);
                this._Temp = value;
                this.OnTempChanged();
                this.OnPropertyChanged("Temp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Temp;
        partial void OnTempChanging(double value);
        partial void OnTempChanged();
        /// <summary>
        /// There are no comments for Property LowPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LowPressure
        {
            get
            {
                return this._LowPressure;
            }
            set
            {
                this.OnLowPressureChanging(value);
                this._LowPressure = value;
                this.OnLowPressureChanged();
                this.OnPropertyChanged("LowPressure");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LowPressure;
        partial void OnLowPressureChanging(int value);
        partial void OnLowPressureChanged();
        /// <summary>
        /// There are no comments for Property HighPressure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int HighPressure
        {
            get
            {
                return this._HighPressure;
            }
            set
            {
                this.OnHighPressureChanging(value);
                this._HighPressure = value;
                this.OnHighPressureChanged();
                this.OnPropertyChanged("HighPressure");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _HighPressure;
        partial void OnHighPressureChanging(int value);
        partial void OnHighPressureChanged();
        /// <summary>
        /// There are no comments for Property Pulse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Pulse
        {
            get
            {
                return this._Pulse;
            }
            set
            {
                this.OnPulseChanging(value);
                this._Pulse = value;
                this.OnPulseChanged();
                this.OnPropertyChanged("Pulse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Pulse;
        partial void OnPulseChanging(int value);
        partial void OnPulseChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
                this.OnPropertyChanged("PatientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TablePatient")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Patient : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="height">Initial value of Height.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Patient CreatePatient(int ID, int height)
        {
            Patient patient = new Patient();
            patient.Id = ID;
            patient.Height = height;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Pesel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Pesel
        {
            get
            {
                return this._Pesel;
            }
            set
            {
                this.OnPeselChanging(value);
                this._Pesel = value;
                this.OnPeselChanged();
                this.OnPropertyChanged("Pesel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Pesel;
        partial void OnPeselChanging(string value);
        partial void OnPeselChanged();
        /// <summary>
        /// There are no comments for Property Sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sex
        {
            get
            {
                return this._Sex;
            }
            set
            {
                this.OnSexChanging(value);
                this._Sex = value;
                this.OnSexChanged();
                this.OnPropertyChanged("Sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sex;
        partial void OnSexChanging(string value);
        partial void OnSexChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Height;
        partial void OnHeightChanging(int value);
        partial void OnHeightChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Output in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableOutput")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Output : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Output object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Output CreateOutput(int ID)
        {
            Output output = new Output();
            output.Id = ID;
            return output;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.PatientWasSick in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TablePatientWasSick")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PatientWasSick : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PatientWasSick object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="patientId">Initial value of PatientId.</param>
        /// <param name="illnessId">Initial value of IllnessId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PatientWasSick CreatePatientWasSick(int ID, global::System.DateTime date, int patientId, int illnessId)
        {
            PatientWasSick patientWasSick = new PatientWasSick();
            patientWasSick.Id = ID;
            patientWasSick.Date = date;
            patientWasSick.PatientId = patientId;
            patientWasSick.IllnessId = illnessId;
            return patientWasSick;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
                this.OnPropertyChanged("PatientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PatientId;
        partial void OnPatientIdChanging(int value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property IllnessId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int IllnessId
        {
            get
            {
                return this._IllnessId;
            }
            set
            {
                this.OnIllnessIdChanging(value);
                this._IllnessId = value;
                this.OnIllnessIdChanged();
                this.OnPropertyChanged("IllnessId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _IllnessId;
        partial void OnIllnessIdChanging(int value);
        partial void OnIllnessIdChanged();
        /// <summary>
        /// There are no comments for Illness in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Illness Illness
        {
            get
            {
                return this._Illness;
            }
            set
            {
                this._Illness = value;
                this.OnPropertyChanged("Illness");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Illness _Illness;
        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this._Patient = value;
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Patient _Patient;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Question in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableQuestion")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Question : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Question CreateQuestion(int ID)
        {
            Question question = new Question();
            question.Id = ID;
            return question;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
                this.OnPropertyChanged("Content");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableRole")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Role : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Role CreateRole(int ID)
        {
            Role role = new Role();
            role.Id = ID;
            return role;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<User> Users
        {
            get
            {
                return this._Users;
            }
            set
            {
                this._Users = value;
                this.OnPropertyChanged("Users");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<User> _Users = new global::System.Data.Services.Client.DataServiceCollection<User>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WcfService.DbContext.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TableUser")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID)
        {
            User user = new User();
            user.Id = ID;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FstName
        {
            get
            {
                return this._FstName;
            }
            set
            {
                this.OnFstNameChanging(value);
                this._FstName = value;
                this.OnFstNameChanged();
                this.OnPropertyChanged("FstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FstName;
        partial void OnFstNameChanging(string value);
        partial void OnFstNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
                this.OnPropertyChanged("Surname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Pesel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Pesel
        {
            get
            {
                return this._Pesel;
            }
            set
            {
                this.OnPeselChanging(value);
                this._Pesel = value;
                this.OnPeselChanged();
                this.OnPropertyChanged("Pesel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Pesel;
        partial void OnPeselChanging(string value);
        partial void OnPeselChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Pass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Pass
        {
            get
            {
                if ((this._Pass != null))
                {
                    return ((byte[])(this._Pass.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPassChanging(value);
                this._Pass = value;
                this.OnPassChanged();
                this.OnPropertyChanged("Pass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Pass;
        partial void OnPassChanging(byte[] value);
        partial void OnPassChanged();
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Role> Roles
        {
            get
            {
                return this._Roles;
            }
            set
            {
                this._Roles = value;
                this.OnPropertyChanged("Roles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Role> _Roles = new global::System.Data.Services.Client.DataServiceCollection<Role>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
