//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34209
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDemo {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDemo.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć anginę..
        /// </summary>
        internal static string Angina {
            get {
                return ResourceManager.GetString("Angina", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć astmę..
        /// </summary>
        internal static string Astma {
            get {
                return ResourceManager.GetString("Astma", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy odczuwasz bóle kostno-stawowe?.
        /// </summary>
        internal static string BoleKostnoStawoweQuestion {
            get {
                return ResourceManager.GetString("BoleKostnoStawoweQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy boli Cię głowa?.
        /// </summary>
        internal static string BolGlowyQuestion {
            get {
                return ResourceManager.GetString("BolGlowyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz apetyt?.
        /// </summary>
        internal static string BrakApetytuQuestion {
            get {
                return ResourceManager.GetString("BrakApetytuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz chrypkę?.
        /// </summary>
        internal static string ChrypkaQuestion {
            get {
                return ResourceManager.GetString("ChrypkaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz kaszel?.
        /// </summary>
        internal static string CoughQuestion {
            get {
                return ResourceManager.GetString("CoughQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy katar utrzymuje się od dłuższego czasu?.
        /// </summary>
        internal static string DlugotrwalyKatarQuestion {
            get {
                return ResourceManager.GetString("DlugotrwalyKatarQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy czujesz drapanie w gardle i w nosie?.
        /// </summary>
        internal static string DrapanieWGardleQuestion {
            get {
                return ResourceManager.GetString("DrapanieWGardleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz dreszcze?.
        /// </summary>
        internal static string DreszczeQuestion {
            get {
                return ResourceManager.GetString("DreszczeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy kaszel jest suchy?.
        /// </summary>
        internal static string DryCoughQuestion {
            get {
                return ResourceManager.GetString("DryCoughQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy odczuwasz dyskomfort w krtani?.
        /// </summary>
        internal static string DyskomfortWKrtaniQuestion {
            get {
                return ResourceManager.GetString("DyskomfortWKrtaniQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć grypę..
        /// </summary>
        internal static string Grypa {
            get {
                return ResourceManager.GetString("Grypa", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gorączka:.
        /// </summary>
        internal static string HighTemperatureQuestion {
            get {
                return ResourceManager.GetString("HighTemperatureQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twojej choroby prawdopodobnie nie ma w bazie danych. Koniecznie udaj się do lekarza..
        /// </summary>
        internal static string InnaChoroba {
            get {
                return ResourceManager.GetString("InnaChoroba", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć katar sienny..
        /// </summary>
        internal static string KatarSienny {
            get {
                return ResourceManager.GetString("KatarSienny", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy kichasz?.
        /// </summary>
        internal static string KichanieQuestion {
            get {
                return ResourceManager.GetString("KichanieQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy kaszel utrzymuje się od wielu miesięcy?.
        /// </summary>
        internal static string LongTermCoughQuestion {
            get {
                return ResourceManager.GetString("LongTermCoughQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mam zbyt mało danych, by móc postawić poprawną diagnozę. Naciśnij &apos;Restart&apos;, aby zacząć od początku..
        /// </summary>
        internal static string MaloDanych {
            get {
                return ResourceManager.GetString("MaloDanych", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć nieżyt nosa..
        /// </summary>
        internal static string NiezytNosa {
            get {
                return ResourceManager.GetString("NiezytNosa", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jesteś zdrowy..
        /// </summary>
        internal static string NoRepair {
            get {
                return ResourceManager.GetString("NoRepair", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy czujesz się osłabiony?.
        /// </summary>
        internal static string OslabienieQuestion {
            get {
                return ResourceManager.GetString("OslabienieQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz poczucie ogólnego rozbicia?.
        /// </summary>
        internal static string PoczucieRozbiciaQuestion {
            get {
                return ResourceManager.GetString("PoczucieRozbiciaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy Twoje gardło jest opuchnięte?.
        /// </summary>
        internal static string RozpulchnienieQuestion {
            get {
                return ResourceManager.GetString("RozpulchnienieQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz zatkany nos?.
        /// </summary>
        internal static string RunnyNoseQuestion {
            get {
                return ResourceManager.GetString("RunnyNoseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy boli Cię gardło?.
        /// </summary>
        internal static string SoreThroatQuestion {
            get {
                return ResourceManager.GetString("SoreThroatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz problemy z oddychaniem przy wysiłku fizycznym?.
        /// </summary>
        internal static string SuchyKaszelQuestion {
            get {
                return ResourceManager.GetString("SuchyKaszelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy miewasz świszczący oddech?.
        /// </summary>
        internal static string SwiszczacyOddechQuestion {
            get {
                return ResourceManager.GetString("SwiszczacyOddechQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy masz silny ból gardła i trudności z przełykaniem?.
        /// </summary>
        internal static string SwollenTonsilsQuestion {
            get {
                return ResourceManager.GetString("SwollenTonsilsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Witamy w systemie do wstępnej diagnozy chorób..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy Twoje gardło jest zaczerwienione?.
        /// </summary>
        internal static string ZaczerwienienieQuestion {
            get {
                return ResourceManager.GetString("ZaczerwienienieQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć przewlekłe zapalenie krtani..
        /// </summary>
        internal static string ZapalenieKrtani {
            get {
                return ResourceManager.GetString("ZapalenieKrtani", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz mieć zapalenie oskrzeli..
        /// </summary>
        internal static string ZapalenieOskrzeli {
            get {
                return ResourceManager.GetString("ZapalenieOskrzeli", resourceCulture);
            }
        }
    }
}
